#!/bin/bash
cd
read -p "What is the path of the repo?(pwd) > " input
awk -v addition="$input" -v targetline=31 '
NR==targetline { print $0 ":" addition; next}
{print }' .profile > file.tmp
mv file.tmp .profile
. .profile
